name: Update README

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Personal Blog Feed
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: BLOG
          feed_list: "https://bumblebee2196.netlify.app/feed.xml"
          template: $newline<a href="$url"><p>$title</p></a>$newline
      # Medium Blog Feed
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEDIUM
          feed_list: "https://medium.com/feed/@sathishbabu96n"
          template: $newline<a href="$url"><p>$title</p></a>$newline
      # StackOverflow Feed
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: STACKOVERFLOW
          feed_list: "https://stackoverflow.com/feeds/user/6506040"
          template: $newline<a href="$url"><p>$title</p></a>$newline
#      # GitHub Activity Feed
#      - uses: jamesgeorge007/github-activity-readme@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          COMMIT_MSG: 'Specify a custom commit message'
#          MAX_LINES: 10
